---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mariadb-password
  namespace: mariadb
spec:
  encryptedData:
    password: AgBuGsrcxXYxGlUZUR+ZHBiuZGmS0lZUKWXmZZ5QCXKRqDcQGkDDdBKWtE3Gd7J/dS5v7BE9Ya7OOWVG6FCnHJaNtkcmkubiC1ooXXWteJnPFh4VFWDJTAvvyqHVlNrtIlxyr3p87+5wA6Bu1eYSmx142PLa8BMpcISxaaT1ZuKFIxMgmmspvfJjcgSrFKEk5c1DT8boYoUi6/G231lPN0kWDiD0uSBXYca+EXqu/uEPRyPrmCGrSywRcp+gTiIJplLpKyUkjDT6XpCxgux1FyMRHtkXms+pGczFyuLvVxbYz0KKP9h9AtJ3O5twcdGwlA7pWplpoYKTt5mdCTUfdoC1qloFPrVITHV5zV86Dsae5smGm33m/63QeVgLB2PR2KxqCQjjiAUx2eZd4z21T89S0tGZex27T6Vx594YDbWJ2ALcKLXCNodQ2JcSHU37Ds1kPA9+1PK+rO3n7f4rwwzb8W1hpRnFSrEvphS3djqVIpaX4LjjzIspzSsCx/TuVtdBH+3vlUN0As9zY+1waiavTozUzs0j2MvLleQ+33gPpbwX/CWZ/0sS/9YIzAh5LqsivV8oaVtFqWZQRa7dk1Ui9kcjRTwsHfWne5Qq3EJhQM/dcRBiaHPJ00/XzHK/iSinvRQ6BOv0qazD03icVnmhFg5vuw0oZWy08giQA/Q/j7o7XMKH+7lZ51DJh90821PF2P0y1+FslbwtRw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mariadb-password
      namespace: mariadb
    type: Opaque
