---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mariadb-password
  namespace: mariadb-dev
spec:
  encryptedData:
    mariadb-password: AgA0shB8+alhLeezV6exoYRUTfF0Haoz5tezGDPkH3tO5LbeYF8kw6tn1vvT3LOTR/VX/5dlEJ2PVAOxHWB1BlyrjzPC+kSh1/J3gm2GNwhVbrO6nYv7Y9vxEdr9rXmSILL0ziFftLjVzkDcjT/r8dq18ZVnCItMKIKHMIA0iHdFaBrc4cINYSx6qvWZ3/m0eYjGPukC2QP1ZxF2Cbh42t5AuubSyK8OWDQGxUXCqv9plbpVuJCGH6RxNvnmkn3LVAQGgWrUZ2VEL+dOa9NIHhLHFApoYjpUoVTqoRtuTNapo5L9uXmYBVYhOu4ey70lFIpAq3q7ifibxE0Mk4EqXzDuBxJK1777c1kc997w/guLVNqcrRO8bjFBZ4rrxwmZ6PIVtG/UQstJVhYaqo9EXP5Vtr0e8aqOwuCRPOWT9e9H3tFfiWgyNSyT0PmKhHhKOHii+mu6EwvOpxUpayHjMY89hFHjmC00mN2srRYMWNMJv7+ynElsuIyfNlJuyTZXd7pCRZxXhq+Zw1ZuISm9HcEs6dkGFhhpa/+MhHra2PESqADgcvhNB2ARqZlHV+jaj46CKzcB29uonlXdTDrCAvKZbxZOG6QZEgd8odtue41WhqEGPHFepeGe6QtNa0Jx0gEoM6RsiRattdzX/1NC/Hn9jE7oBfqfYJ7yqKCKcDaMp2OKMyS6r/EfDYOWHSodqSxV9z1IvmmxoPnmDQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mariadb-password
      namespace: mariadb-dev
    type: Opaque
