---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mariadb-root-password
  namespace: mariadb-dev
spec:
  encryptedData:
    rootPassword: AgA6X8KPRWwmuGjDNTUCebaQJhIMYjZcd4H3lcM68QGeF8uD3fOiElClSMIGtJoz27ayxeM2Zs/bsRuE1RtL7BoYakcX9We4UvD3i4T9mGlbeqTGyrf1HBFJXCVKNxNbHeSZv3R5RvEEYh69S8x3J506KSGW5l7eUHZTcmtP4J9xWTJH6bnmE3BEteCwF1soh9gZIew30LWTTzyQ7YvNrupZ8kexYclZuyaWl1PGEQojszrAVjjxODTzf+2bIqz5kdNsCfXq2E0qSahDCBgicWZtfDpWKxDhsLCaFeBkLsBi2+q6K2saFAdYDQHvrSMBQf6MjDxBsBL4WdS5Iz3+rvrsZXoq2s55vend3msRscOoXrWMJTEQ07bjeDx7l0FXLcaCHO3iRAPLpiWB5N6CmMz96ganIk5n0D0GXd+Ri7v/yNIUvMuXeSNdzusAKqrQ5dAP+d0FuHCimCyc6sv/c/tTux7tsoTk/38ryUSCpEcGTTqq/Fpg6AKBxh2yDVdUQjxQQouM64fAUfKJE7ZFIC3haaLewXm8wgQaDd3rwFzOPtRAE2QNFNR/mFzohPBzWLFHgmgm9hzqJb816gCj+BcJWty/jMTKdHeYycaf3aSczafKg9uh592Zk/nOdhsrUuxsAhj6b7PNubYI2psE5cTDliUFd7VdyT9mB7E92rZ19Pf4TzwP7ympYjMLVEelRuBycz8y9RaxumH5sQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mariadb-root-password
      namespace: mariadb-dev
    type: Opaque
