---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mariadb-root-password
  namespace: mariadb-dev
spec:
  encryptedData:
    mariadb-password: AgAPziaVzY7xSOxEfIutzCO/0bNfZ+29YPRHjG9TCYChyFtUNzsXXkQf7A934h3tna8v6xG7iDCZMoVabnW2datODZ1EEaKCopGArP+Zavp2zUS2tIu5P/nJtIcAq43ZHikXEOwa91s+PM1NEl81h9fhS6PpyRg797QgDnV1hHr/7R/TpOKV4s8waJRkKhlbUBvS6ldn0WvyJLjkf0elOHaoC39qsTOymN/v7hRp7usdT+6Nwoc0zdHZZTi40uw5Q9VJa0ZuzgimHh48UfLWSKC3ClgUMIizYk9Wj2v8Ge78BRwFK+OhllP5MCSVDlSB9TnCpcQumxKsGzC96xBijmU4socfzYJaYsAGjG6aw/X6OLhPs+eJdFAFHDpmiyqTCUZ0RSFCcTaG1PESsQdeg4qNvNQV6UqLjsqdZsBL+2ThT+UE35wxeCoE12ENVk+mwcuYToJiLzjkjlDnZ9d6oEk8WZiGxKQ8ooZW+dQqPmqC9v4dAiburIHQB3BMwYHKl2VyUJ+Czx/zQKF6WyYwUfTgF3/waaBKjm0DtYd4TQVfHngOKDi1AjBHfPWnR3geaeJfSlcMCho/2sBsltEw+LhjIk3f0jA/u/tdSa4DfK2iqr+z5G8FwEb0xJxPS4iA8rGMVr6CYT2hz+PDaTSY7gmtb6nbUtc2O1UC3smW36Y5WXRcbLQXDugOR0EfM7K1qYVCHRV10K51LlgqzQ==
    mariadb-root-password: AgB8cLLvG/CWbzu3gch8dZ9nWlOr3yXqX7rqH7Rt7xNUz+NPr+VapWHzSD8QRYj8AJ80PhwbPd9C25gFXe2EO17BOq6ZWvBKZQwcbjIqDqGa8F6m1WTF9eLJVKaElzw+DImpv2eN62cl/Des4Tpyw7MDVY5IVDZUNejhGt9rju1Irf6QSViDIqSEo6kfsDecEyx0/xU9tm461PUnp3eil53XK3o+SRMaeN5Dqv0fhUo02lswohc/6h8+PtHvXd3DDOJqf9NaiT2/bawJv8wKDl2nLvOXLqnmDfgnC/SKz6svccwppPw7QvheC+p9o4wFxOB5/LXZMCdEQRhXZWIuAKJ8fV8/6GDeiXZGqmLixapCUCSKYqbZ+wcIZuX+iJOJIsXqXSIBbBlpRzrxr2W9bulxOpO39cO72es/W5az2dKfHitxvCB9xeoLuuuJrx6L6PqKrKybWg6ZIdHU9biQAPMM9sJHKF6MhssecjAhUX6cJzPV1MhK0jW5bxqqtYaxARYQhMSqroYqcOItR3aYx42HVMOOcGYc//3HxC3L1eKAK0cqceEulGoboT3Ca5sLiGqhLS2Tl3K9LRC7JTm4QJiOK2lh2XarKD6EhrXwniQUEgdGLishIeiFLUuHvqP8vr6AU6lCwwmMRYPXT+Fg2jfR8lwo4KPNo+atBSA6ur0KlJm9DQ+5/QOkK8mf+Di87RSC1zKaK13nVoRPhA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mariadb-root-password
      namespace: mariadb-dev
    type: Opaque
