---
apiVersion: batch/v1
kind: Job
metadata:
  name: umami-init-db
  namespace: analytics
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: umami-init-db
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-db
        image: postgres:16-alpine
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: umami-password
              key: database-url
        command:
        - /bin/sh
        - -c
        - |
          echo "Parsing DATABASE_URL..."

          # Parse DATABASE_URL: postgresql://user:pass@host:port/dbname
          # Extract username from DATABASE_URL
          DB_USER=$(echo $DATABASE_URL | sed -n 's|.*://\([^:]*\):.*|\1|p')

          echo "Checking if umami database exists..."

          if psql $DATABASE_URL -lqt | cut -d \| -f 1 | grep -qw umami; then
            echo "Database 'umami' already exists. Skipping creation."
          else
            echo "Creating database 'umami'..."
            # Connect to postgres database to create umami
            POSTGRES_URL=$(echo $DATABASE_URL | sed 's|/umami$|/postgres|')
            psql $POSTGRES_URL -c "CREATE DATABASE umami;"
            echo "Database 'umami' created successfully."
          fi

          echo "Granting privileges to $DB_USER user..."
          psql $DATABASE_URL -c "GRANT ALL PRIVILEGES ON DATABASE umami TO $DB_USER;"
          psql $DATABASE_URL -c "GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_USER;"

          echo "Database initialization completed."
