---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-root-password
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCf/3RAdqGh0MmSe4vzRWODhXoaqKhVa5gaCuTQPxyxvgrvIUYCX6dizHN39OQnxfwyF8cI7Ix2sEsjxrkOfDVjJqJuNWI38dC4MRit/4krD8eNG0nT3IglCYuMGdOL5dZR+1VmCaZbe0qRS0W4piJLY8oA1l/C6H98WYZhlph7bPZxmE5pHmLMNLsBcKugiSfqmy3P9TiTisTmUMtgR7znhvJOPYiGXur24wAbREgiedcmiK3Ii1TBMQQwBIUZC9Zu6wa9f/EA1IXONOeRN26MRZmKg85wDpa4RpG5wMPa6z29WSjtMEgKug+s6OQ5Qo6Rcd3eSosX5CSKTAfGlHnCbvvXQpIrKIkbtnLdSdBsKjBVRl+xK1JWbM65fjMumAq6e+q7of7I9kBGgazvtVc/DModtWBPw5JEqluO2DgweBL4AXIMv6DymF5AoI85vxQweqoBL7jb55x8iAkrmAWMB8TtHEu01/5LUYbZlaw5YT+n0ZZ+oiCtnlgUijOOrgQgkVAuQtQOwGK3waMAPe4Z9Bx6tqbCql9vZfjykmz0TX+ha0XdJbbvRitQ/jWMLyRt8vlKHqQtcHt/0fm25ilmV5pV4Abm/UhuhWHiG65u8CpkeDioPztWbYm+Wx60cbcUDKA4Cks1rCQUaFxt1fPr8xjoyL9bDxvJbrOK5ljtDWjvC0Cn4E1FZzFELWv4J0Ehbt7o580OTClt9A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-root-password
      namespace: minio
    type: Opaque
