---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-root-password
  namespace: minio
spec:
  encryptedData:
    root-user: AgAnwyMxkbchgtZgthLRKUUEhQNuWMwkuQqAArLAnk7xIVMCTC8Td4LMAgmOaagfX1X1lYo3CKi+wFTXjNaPKM7eVcK+xR78nQtzm3xxChSAvPjGIQJZPIEkItQ/w75oWoY26qOEKFnWMYGNpuRjo0XJi1KOOikmvq95PKzX65KtueDksd0WikLec5fvGwjn4/j4Jym+2MPApfkDPVu1dCM4RlNAa6tmzPt9lutZnsS93Sxqn0VRieBr5geShMl8dLhMbAzcjH+jS+gY/5TDckuKLUQiF06oyOIz0siDqtrMD67HWFZbB0qdtyTWTw5cdek/Icbd5Ocg6hOHfFYeN9zAGdPMEDrghfXjIf6K0X25Hz3ZsCYZu24X43jhrZoinUTccuYL8wkxvfYWu/DhxsZxXPhbU3aO6VchlCBxpFpDLcegDRbD59TFGM3axvKZxcTQxNZhLWMSV5NfntQoCdtjU9Zo1UMolZ8zG0U9Tn347omcXQcSK5RL3v1g6r5MEg2lMqSabc5rFgm5SSe5q5sd6obqN2nCXhRlWPW0KF7DVxqXxOdnjb10fJ31DSmsscWdTuIztMq+VcZw8E6EAQClDkJHnVEBgDu/2LLuls38Bvp2O44MDmJxxgq5ds+Sj/S4yHGj1LMOuu7oMAB6aStU8WquDJRRIq2pC5MuZs6locivFuXJ5hmHzMNvAZE4XvfdTmvHo7hX9mA=
    root-password: AgCQ7uNxdfQ/YH1oulOz1INJLY5nTVcic1reC1RYtaqYoq6tsQFRrO4Xbq9mFYjXwGjimVSIAlhIM2tuEZ4exYVpEVkWq78p67Ck3rAU7KJpJE4odqw/4bHWzwO717s07rxtur2HBC/L0FO06kigpVqDdZInXbFcagX5c4uy8kMa3Rpq4rulvNj4l1/VC0KH8hYW0lCb4zGztY3JKHqUeC2QSsrv+1J27LowusFoUIHqS8/VJrNps1Vz9P8fI2cqAbd3c1x/mDcIXkJyRLfVS0A4lqfSEKsNBoRxeh1K3zHZeIenOCBNq6/hFGnKv0QxuIN0hlg8nKWZefLDLqvJqEkmlCJlk5hThVSCWwe96BXQZIBX+TJ6QTEuTf3TpWI+d55PnM4K4P730/xKHdLTZx0+9Yyz5NjQo8lX2nDKsvU3HCKjTutGnCYxCRqI8b+tYjFZANfhf8MIIXfWSMWT7uGlTTpxRc6/W3Fl4CZ8J4+ybFowJt61i4HtwElBGBBUBTfW0QFZkzD/J6CL/MyFvghDCD2QixvvDSX2kVWMS3s0482yvgWp3fwVCTGBUiutTD7k2J5ahlCUHXASxfI9u1SD28o45aMzTCPn7uKf12OfGodIcpSIdTgriBzHInqPfsXc0l/VrC0Mn0KSm2mG+aHBom0R+s/VAx+FkLj3uWYg9kcw8qpQMoGZsW1Aq+ebZ1EoVLWDEVXV6KCBhQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-root-password
      namespace: minio
    type: Opaque
