---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-root-password
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAVP3MtJ+raam/KNkXm7OSw9tFNfj8VI+OFoNSOADdZ1epuWUWpGbFlcwiGnc4M8hdvT1ShjldfCCtEGwRl4MteIJy8AOHwGum++OTETv9NhQcULMU7RIRmX1a7zQBiZx0gJwEG+r35JcZJU+Ez8xGFSSrCA/06G/VhG5eTxW0kGnlHDNpiPNxrbpnd0iwu6x7iLmbmX9w7W0pWslqIywF6SnzPJrqxisTTzqGFf/SFuQfzyf+ZJ9e+nfQSDSQagNZWr4EVsz41gUy2db0uNRcml7chi33B7uSSL9q2L77FLR/0KX0Dx0q5d5Zy04YOig29GqelLJFV6+XpId8liodq9niifIPLaH7IDNw6C3ol1YzlnkXfZm1YAAzt27Zy5vOHT/uj0t7ygplaM42ltbx3091XM1/fzW/R6khvDK8lAR7HAGAiIE0RuLTGo9GF3/G054PtNvoQcqHLY4odT5Wx12wxnf0QqBbjFfZXlPsWMMjAufMZ9obs1GbnwazRpOmc5NJS+4x02OYsm8lbesPGuGymY9eEEcYiY4W3gzycXb2zlz1X7+BODH2N8vdGVcZXy3ZTkmy12GmUaC+0usYV4UY2ZTVXl7ZDYQKIF4qz5MKHPLP0n1W5cYhGhsQe+ivWpvDbiyfHQ4PHj5BuhD7u+HGFzTaNlFFGoQ1kzYsDT9QcLfRcNsAESjVcpakcGDP6XQF7luHnPKUU9w==
    rootUser: AgCASc4h2nkks/eKZoMjQ0GeN1tRdeDVpcrSK5kQ+L+uNwCBP6NMysZXDhQW1NBkGGnj7QWeA6SUzTeh9Uk7IIdufx7MYi/+bXq7JyFXyRFu0gQtLfthFoGcenuAJTFSD6pewUsDrjXsgj2Vm75sDLcDOigwBwVDp1f/DBmmNaNx+cNQcB65FIHtLmO/BYeMC2Dmm/8eHPc9td8o3AAz96cAlEedVyJ+dVEcIL/T2K2/crNu+piieecJW3V6YbMOrxNkVtsx4o2Y9sf47MC0qRFMvOz5gNt/IeXFCoS5Y0q3HVcOwZUB8h9bLrF1hMp8RqbBo7kB7I11aWeev0JaNaei8igDHDKDNtrnsQQ1eNQRGXbheH3/zwxc2cdhyD1ibGzKrsiJinsWWVXHUqU6j+AEdrL76eu+t4LCSXw43gkSbzS8xBmDDxW8RKZQ0pAyYj1LQ/5Xu68sy2elyTidN8RrwOBQmTUUlwIwwgJzV+XlreVKSm7UKpTGOdofsA9fOyJGRDs5eker2Y3tWPUgrctZLYh3+H73OF0U2DDsHpUM7LahLAwDsGVrFk0RgYawaBIN/pwCQ5M5/J6EoDN95/RUU2o1q/FoQkR6Z0V1brdN7YZ7iVTDMbg+9Ik63xYRi3hoM2CRcOa4Vmg0GA0NbVG+7B3TCkZFUe53JV2ioVzH+Ai74+TGe6AzgbhKorRkvf85LTmKmIr3LDs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-root-password
      namespace: minio
    type: Opaque
