---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-root-password
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgArBg1HVHPv5/4FBFUL2c+B5QpkxyEhMbrBqQ74bgZzZ7iEctxBO+tRRfz76BVBBN0VSSP8aDf19nyEnvEBYDlRvadrvBUjrlPPqy2M5z4oo+jMcuX15WKnsVRG+wi2Sy24jsXx+/HoVkVzYyQmaSicnSf9ZjUlxk+xK5pk5An8vHcozO5Ytvwi8Q+Hb/gtDeOaOpyzZ3q3bi/OVkNJ3Y0xRYMV/NM/zBS5ckgsuF1sny+ul+wJQ2F52OMrx3DMKTTFckQ2UYbQOr7XDaMIAnGye8Cqjm35uv6i1UKgb3fJwqcXwo9vGEg6QD6WI/ag4v23oPPAJZSGhcgd/bRU5n3P1Ai6TV7yS6ANxzoMkGRbQjVcF0tCpmjCwJTcJ3qYmSwDy6BnQ2rCpxInbg+HwUkqvmcHTt9+LSY5i5iUUW0ZgH8TxirIe0rST5QkEh8jnHSDPAIbMhJeEZ/mTYMCz4LG41D8RYZEjvqvwAxuvPqyr1XNDIGxdicjnNb6UmXOWuYpaMdQHjhV5ow8xs+NJdlsuyThQ55PZNO6Vt/hlotAuA7gLcqR35DNBCbnksQjj6zmUnQYFmxySsuWoWvEPjJNsjcypWGWtJ+4Y/PgdBJzwxX6xqY9VxsZ+cnPD9llWpRmlFYu3exPrqtK3mrfMrSZ3GbcW1SclC998RpJntjxCMJNYENplBrv9X1wOrctmefA/srV1taLSuMb7Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-root-password
      namespace: minio
    type: Opaque
