apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: gitea-postgres-password
  namespace: gitea
spec:
  encryptedData:
    password: AgAoyFQsHmBaVS+itHNqXZRLwrK3pGj6Cz5B5FG/eNOVBYATwyKsnKb7umHC6m265hyf4ltmm7ITNc28Flh1eWpcKKwWFX/FUcCT5VaL1RTAmUKDYdMkQdCKIM8gPCaRBEzFn3H2vGvA+Z3WED9VFcuKZSfNJBZ1VF7PramHnhB6YYsxtsJiJwxVVwXbIibCz98fL4lCKz6+IkLxgtyGnMr4NyKdEKaZucWPc4Qy6GjdVI2/Y9EXjf3KAdBC+/bqROYQs7AEnbaqXez5m3JpQIq2/vrfYnJpYDSiBDatxSjt+lXugcLEuUqRFgLPS8GpmUqoFDG+OFDCrCswtUWAV7PV2+j+NaQ3oJ/up0ITPNBCZtXDA5JBsDciTOqpleVr2R3EZLHUlml0DxoRf6wspesUcwjzgectG+vFg9SJmH3KdvJ8pZsd9IgK40iHzH6Oa0kuTuK/qOyFj5shOPNruEdh2/N5rv5DlMKCbDM0LYGNNvvHn2X/iupvw2JL3ZLBaE21/CB8ZU//e0HpEGqfhskHLaVktIAMVdzcoaXOWctShyY8O+/BjJpqVZZ0iIcNqiFXi451/bqSJctpD3PaF5swEnh3aWusJ6P0TjrfnYYii+3uRKF151wSzUlxHxTakYf8bP4SwFqdjo5X0vxDfScXWwzfdVt/JLHCM8Z8+9Uja1zeafnr7HfAsYg24ju7cJyip8Rch66wd8MyxJw1JA1TA2NyCHrM
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: gitea-postgres-password
      namespace: gitea
    type: Opaque
---
