apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: gitea-postgres-password
  namespace: gitea
spec:
  encryptedData:
    password: AgCH9UjP1xawfdPT7zHCT0XcSmJiLRLvYb/9FGu6CbPzkuZsnLZmv+Cst83GqM5pvpYfIga65skmySnjmE3GdTvmMtNEENGjn6rUy+Hl1UYGn0v9Z9moYsRISVKgasYnvXcRakrVX6Ht5IQgzaZo+EZdHappJFlbe+rTxVgcXE5sMK9KKfudNSRYhJcKPbD+5/8uxT/A3vs94ZRtwGozn/5eIZjgT17BmXQ33oH0Ud2otHATCHNksCSTPdBam/2ENbu/YTeu8bZSxEosdXftLcDnBM06iP2rQl9jaibXu/FVsBrqsffjioReErjOH40HzqH4ifCIJppsBfcqau4oGhnsDmsAAmwnxy4o03as/R5PA5FmFSBbM37q+Vwn3NAN/iiNZAuSIW4PHmbOjeu9vXSbzRDvfGfzY/Chq0gcOv0RSJlq0S4zVzT5rpcn64UeaiGquWnwqRPmSPQw9itVmn5ZJ++IKUGnEE7dmcvLHkfvhfd3XFo9m+b1/vWEkIPFLyTTo3MWPES2SaTdkbfpaeronFKTT9nwKP4GmPvxlIFga4/0ynavnxGXkW1UW4AHl0lRtpqcIGSPOmkz0jgspvbi0RMK0vaPFVrYfPcGS8WtT03Sz9y/lQSEf1hAj1cKObJWCGFNEXu0e3Bm+z1C1tJh2JtnX4RE0CDqSKO3p9Py4Cbvr9MrXKsoMFGjrzChzK760rM4aEiLBxsrQQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: gitea-postgres-password
      namespace: gitea
    type: Opaque
---
