apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgA3LZ5nFFgJthOU2zQZ55InVB4nuooj9x2O6jeV5U5dXmLe/8vrQMGKpbncGFakrag3sQ2GOCSR1OL1btNqVE2ktcxZLBp/UsP/fpI/CZJzN/xvGyLts4LcWMqBYMYArgANHoFEUgMBnMC84RJGk/0jVIVvkBhsxiytNxcVp7H3JOjas9OQGMnx0dfNVOvD6/2jKtR/BUTeJj3MCdcBGzpJiaD3FYUhdcRAsMH/dkBntAvXGDczpVJXEi7+z9dC8JqAU97AQDQt+QIN5CS/zn13oWeU6gtwYEVuyqIQF9ytD2fOhzFwksyDfQ/VkWKTJaTFG3/TUGjfD1QXrzVZRwZdhB7YRBREI7DnCOpdomt6Gey/gFrljS0NBExp1XX1R6h/fWUBSH4A7aqFgKcANiHH2OL0BcO08m3rKxQYzTWoU8g5GRy1fbnCLUcIbvAU5VjCoi1ImkLgNjFS0k5M8LbdXRLQ487WsEKcILWj1+u59iLjMOiFxgLYTkdCClBrHE5m+eNCAptxume1sGpsXZEWse7+ko8iAwwKZ1Mysm5Sy9O557xxbkx6E1urEYdzA2qRtrUeKn9p8uvhYAxlPhmDLwKmMRZGUvy6vOuGv6sT7oTUXbQgJUC3ro6qBLg0F1/2Jvyv0DfWfweqOOxh42wWUm3ymrdgCE7DWtldae3XgmXTrSjU9XJyV4ndYAnTRiSPQKCIJatJm2Pm2Q==
    username: AgAlGRu64QH/CmokyYUdfdre0mOxeB05/48eTMSkViSSKG7pYm7BDUopG8uRUg3mWmqU5w7LgNprSk6Sq4DLik/omoCZR8Ibm+LbbxFPWjKTyvqZtRbsxX7qeoZT5YI66wVXxtyTToP0l0XQblWs5WG5o9RblQqPar9cM03UG4aL/Cc56LsFhapNfyKNXc1zmAE71RSaP2/NkkJjeHR1zwMaAeNfgFed1EZFEdgwMtZB3z5Rg0+9RCehr8IjuCEbHYyaiikbbXGwJBmPpLb8HN9TOdmM2OVgb6RLtS+JkikGY5vgJi3silP1tCFUqM8NuNi7gAnE9FID5QXFR8w2/pvyMxRKaO0zZAU+gyMSl1Yb/a36hj0OSP1wA5tcADIxH9H4dWWR+f8WxfyD0CY/U+JE7ELOM6LrE/QMtsqNVJtVcNL71ljzxAUz51/Dr2qGIwfqbvyKGhNVI3bwoOzPto9BjPNIj0Q381hUebCLTkLZcHm6cb7W+SinyCoBaOKz0PNnLN+fTrOkajR3KEl5c+4EayFTpGlaHUq8TcDkldOj9LjgI4KP4ywZ9fOyAA/ossTvjmturBevE7zaSA2zbaBbC2yRYAHrsG0J5LGCt7iqtOfMDzu0ntuH7FhLjn1UYcpeUkY43HqrIhus3Ot7ZllYUmivJbhCNXP/12iauxaWgKvZkW40UKASfmWdXqK10Mk6RPraTqzLl8Q=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
---
