apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-backup
  namespace: gitea
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-backup
  namespace: gitea
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-backup
  namespace: gitea
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-backup
subjects:
- kind: ServiceAccount
  name: gitea-backup
  namespace: gitea
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-backup
  namespace: gitea
  annotations:
    argocd.argoproj.io/tracking-id: infrastructure:batch/CronJob:gitea/gitea-backup
spec:
  # Run backup every day at 2 AM
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitea-backup
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          initContainers:
            # Scale down Gitea deployment for consistent backup
            - name: scale-down-gitea
              image: bitnami/kubectl:latest
              command:
                - sh
                - -c
                - |
                  echo "Scaling down Gitea deployment for backup..."
                  kubectl scale deployment gitea --replicas=0 -n gitea || true
                  echo "Waiting for Gitea pods to terminate..."
                  sleep 10
                  echo "Gitea scaled down"
            # Install kubectl to shared volume
            - name: install-kubectl
              image: bitnami/kubectl:latest
              securityContext:
                runAsUser: 0
              command: ["sh", "-c"]
              args:
              - |
                cp /opt/bitnami/kubectl/bin/kubectl /tools/kubectl
                chmod +x /tools/kubectl
              volumeMounts:
              - name: tools
                mountPath: /tools
            # Install MinIO client (mc) to shared volume
            - name: install-mc
              image: minio/mc:latest
              securityContext:
                runAsUser: 0
              command: ["sh", "-c"]
              args:
              - |
                cp /usr/bin/mc /tools/mc
                chmod +x /tools/mc
              volumeMounts:
              - name: tools
                mountPath: /tools
            # Fix /data/ssh permissions for gitea dump
            - name: fix-ssh-permissions
              image: busybox:latest
              securityContext:
                runAsUser: 0
              command:
                - sh
                - -c
                - |
                  echo "Fixing /data/ssh permissions..."
                  chmod -R 755 /data/ssh || true
                  chown -R 1000:1000 /data/ssh || true
                  echo "Permissions fixed"
              volumeMounts:
                - name: gitea-data
                  mountPath: /data
            # PostgreSQL backup container
            - name: postgres-backup
              image: postgres:18
              command:
                - sh
                - -c
                - |
                  set -e
                  echo "Starting PostgreSQL backup..."

                  mkdir -p /backup/db
                  cd /backup/db

                  # Get list of all databases
                  export PGPASSWORD="${POSTGRES_PASSWORD}"
                  DATABASES=$(psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -t -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                  # Backup each database
                  for db in $DATABASES; do
                    echo "Backing up database: $db"
                    pg_dump -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d $db -F c -f "${db}_$(date +%Y%m%d_%H%M%S).dump"
                  done

                  echo "PostgreSQL backup completed"
              env:
                - name: POSTGRES_HOST
                  value: "postgresql-primary.postgresql.svc.cluster.local"
                - name: POSTGRES_USER
                  value: "postgres"
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gitea-postgres-password
                      key: password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup

          # Main container to run backup and scale up
          containers:
            - name: backup
              image: gitea/gitea:1.24.6
              command:
                - sh
                - -c
                - |
                  set -e
                  echo "Starting Gitea backup..."

                  # Create backup directories
                  mkdir -p /backup/temp
                  cd /backup/temp

                  # Run gitea dump to create backup
                  /usr/local/bin/gitea dump -c /data/gitea/conf/app.ini

                  BACKUP_FILE=$(ls -t gitea-dump-*.zip | head -1)
                  echo "Backup created: $BACKUP_FILE"

                  # Prepare backup directories
                  mkdir -p /backup/repositories /backup/settings /backup/db
                  DATE=$(date +%Y%m%d_%H%M%S)

                  # Always copy the full gitea dump file
                  cp "$BACKUP_FILE" "/backup/settings/gitea-full-dump_${DATE}.zip"
                  echo "Full dump file prepared: gitea-full-dump_${DATE}.zip"

                  # Create database backup archive
                  if [ -d "/backup/db" ] && [ "$(ls -A /backup/db)" ]; then
                    echo "Creating combined database backup archive..."
                    cd /backup/db
                    tar -czf "/backup/db/databases_${DATE}.tar.gz" *.dump 2>/dev/null || echo "Warning: Could not create database archive"
                    echo "Database backup archive created: databases_${DATE}.tar.gz"
                  fi

                  # Backup repositories directly from /data/git/gitea-repositories
                  echo "Backing up repositories from /data/git/gitea-repositories..."
                  if [ -d "/data/git/gitea-repositories" ] && [ "$(ls -A /data/git/gitea-repositories 2>/dev/null)" ]; then
                    cd /data/git/gitea-repositories
                    for repo in */; do
                      if [ -d "$repo" ]; then
                        repo_name=$(basename "$repo")
                        echo "Archiving repository: $repo_name"
                        tar -czf "/backup/repositories/${repo_name}_${DATE}.tar.gz" -C /data/git/gitea-repositories "$repo" 2>/dev/null || echo "Warning: Could not archive $repo_name"
                      fi
                    done
                    echo "Repositories backup completed"
                  else
                    echo "Warning: /data/git/gitea-repositories directory not found or empty"
                  fi

                  # MinIO client setup
                  MC_CONFIG_DIR="/tmp/mc-config"
                  mkdir -p ${MC_CONFIG_DIR}
                  MC="/tools/mc --insecure --config-dir ${MC_CONFIG_DIR}"

                  # Connect to MinIO
                  echo "Connecting to MinIO..."
                  ${MC} alias set myminio http://${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}

                  # Create buckets if not exists
                  for bucket in repositories databases settings; do
                    if ! ${MC} stat myminio/${bucket} > /dev/null 2>&1; then
                      echo "Creating bucket ${bucket}..."
                      ${MC} mb myminio/${bucket}
                    fi
                  done

                  # Upload to MinIO
                  if [ -d "/backup/repositories" ] && [ "$(ls -A /backup/repositories)" ]; then
                    echo "Uploading repositories to MinIO..."
                    ${MC} cp --recursive /backup/repositories/* myminio/repositories/
                  fi

                  if [ -d "/backup/db" ] && [ "$(ls -A /backup/db/*.tar.gz 2>/dev/null)" ]; then
                    echo "Uploading database backup archive to MinIO..."
                    ${MC} cp /backup/db/databases_*.tar.gz myminio/databases/
                  fi

                  if [ -d "/backup/settings" ] && [ "$(ls -A /backup/settings)" ]; then
                    echo "Uploading settings to MinIO..."
                    ${MC} cp --recursive /backup/settings/* myminio/settings/
                  fi

                  # Keep only last 7 backups
                  for bucket in repositories databases settings; do
                    echo "Cleaning old backups in $bucket..."
                    ${MC} find myminio/${bucket} --older-than 7d --exec "${MC} rm {}" || true
                  done

                  # Cleanup
                  rm -rf ${MC_CONFIG_DIR}

                  echo "Backup completed successfully"

                  # Scale up Gitea deployment using kubectl from /tools
                  echo "Scaling up Gitea deployment..."
                  /tools/kubectl scale deployment gitea --replicas=1 -n gitea
                  echo "Gitea scaled up successfully"
              env:
                - name: USER_UID
                  value: "1000"
                - name: USER_GID
                  value: "1000"
                - name: GITEA__database__DB_TYPE
                  value: "postgres"
                - name: GITEA__database__HOST
                  value: "postgresql-primary.postgresql.svc.cluster.local:5432"
                - name: GITEA__database__NAME
                  value: "gitea"
                - name: GITEA__database__USER
                  value: "postgres"
                - name: GITEA__database__PASSWD
                  valueFrom:
                    secretKeyRef:
                      name: gitea-postgres-password
                      key: password
                - name: MINIO_ENDPOINT
                  value: "minio.minio.svc.cluster.local:9000"
                - name: MINIO_ROOT_USER
                  valueFrom:
                    secretKeyRef:
                      name: minio-root-password
                      key: root-user
                - name: MINIO_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: minio-root-password
                      key: root-password
              volumeMounts:
                - name: gitea-data
                  mountPath: /data
                - name: backup-storage
                  mountPath: /backup
                - name: tools
                  mountPath: /tools

          volumes:
            - name: gitea-data
              persistentVolumeClaim:
                claimName: gitea-shared-storage
            - name: backup-storage
              emptyDir: {}
            - name: tools
              emptyDir: {}
