---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgB5tq64QFe2UOx0FScJyX19MG3pydfOsrv0Mq9CIFsbsCQVONEGSHaTT4x4l489AMZFLINv/lBSlDf8ZknpKIqzfEwlWV95k9hiiNvvvpFaHIqTKiYNsWAGvzH1pHHC6kqlLw2WX8AbP0IZg5CLdH1Q6Pn0JP1ZbwhkBS58bF7hNWwyWVDogKFYCqvrTKqTWG2Eopy0uoORE0wgiP/7MI5CkAYeAV3U7Yh/xlZm/xqlnQqMC0MxA00DUt7P+HaauVpLjP2tJ9Y59figmfQfP4U5hy8GKH2+Oe0r+QpNaM+/Y8lGU1v7IRmume4/bPibYp3gu2G9FGNOFLk19RdyxZNXoKTAWwhwQ8WGxf0M3FUyh48kaQmwwC2qJpfWs4pUNcTuiTR9fbIk4gJUIO3Xr7MIzDSXPAhGz2WhO9bOmA93uufm+DDGVHSPaUDbbJhXJo8RmPt0jMxcaknO1xgWowSBV7wiVL8Nz08wRo9e+XTcZppYTwpmOQ7HF33dRcp9mJKETfuL4hCZwnckiZXVfBSqpZWff96/ZIS9jEzBBBLP8vgJqbdL8u8l9hXeP+1wvWVUh232MNDGWsrDeK7+mB2wEXqBSCftx/ub0idtiwf2a4+s0rd+GZ7ULIpLhSIpb+zS99DFpBpsJqPkQVKDfC5S2k5W7fwOAPSqRfD03c+ZmAtBF7XKcUXlXTbTG3wkxMlRH7rU7WcNkVI=
    adminPassword: AgBUJ7jks4SSbhf31t/4UheJzWWyvqpOG9FnX73zNe7qCddBRaIwLdrhUCLurETmQGUpYullZxbmS96q89JdIK5M5pdvWmReXy3bO/HJRcJtHT9T97sBi6vmAnvtS5MVXhTbc1dEo/hIsvx9n9tOhhLmpdijW4Lg3NOztBykmblMXdKpeNKIdKEjn7qQTdGilNg/W+UNgiS3wlut66v4caYUuq9VrE07itH6VkN+Srm+CxBcGvrYyQFwy70gD3u57A9dawL9UCi7HfM4ycpyDNLbJCkLgBWDZzT/WfOL7ClvRuJLvsTbO+EFGnffWh+6ew82CeQsbL3Ykq2+ugUPRX2eIICPfRG3WoBWguQHq2DJ80xkvKUCh9BtC0LyFgIxvyaXwyaGHR1L0MRJfshsqAExea1apV/2mssMNY4/NTn/wbExSEQn+o8cc9rLI8uvJ+0cnjT71TGAWFFwxpKiamcHW+NzUexMTFTvPg4S6hamxs95UKUUobT6TErfp5nqxNXePJ7RvaInTPjq9Lrh6pQOUyLR9YU77RUkR4kBUT1wtYEVzZmaCnbeO+rV0SlCbEtJzGZUMU1Clz3uvFJ2nG5fCe2CFQHJIbfBPeETdPH+YryUTPWhbOIH8ibXNmeXSLqlV8Hz0kVl1BHdp2hb4lezHxgQ+4FwgnD6BGmjZ7ef5rWAO+7CJy7xlsrk5vUMq3U+cglUw2e2Yze+8g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-password
      namespace: monitoring
    type: Opaque
