---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgAn92PaeMn5SaxD1rlFV7Hw6qxYKA7FYfzsi86J3aE+rmuYxUPwkL0MMouWZ8iyapaf0A99q7QsJ+GrKjk+WHfq1SaQjtZykEPHjxywgSNDEBcaZq/4kvg+kl9idufEI1NWpFyhDeOyohF3UAYFE8KW9vbp2ALHTBut6yaMRBqUITMs3rGUP4ZZKy2yr0lvd1Bitk6ut8gstMAzDDClBKJjXMgYFSqWrvSfUlWFIdyz5nfYK7OvGtDjn0hJlpb72ppksCwR2JTEQhIb0CrtHQIjKdJrhovfKvv8DD6bsGkg/hrKTjB3hnzzFid6svCyd71+ynpV/M8R9mw56tGm0Iz17SZzPK4HXl7rsZvEhyi9i8bpXtMjalgA+89re2Gfj0LMZFA++n0DltuIhWqPZYXP4uVvG1xBDUASTU3k5nIG4eBSeL+cVy22uoqmZq6/75ddGnnSpQEBrSXWeSnYojMXogWK8LGSKr3nKAwj2k+XaeTjCQV1ZcJ33Iief8HRadmBLlWqWHZrRCts8LNM6eVwsRaGBPbFxo6s9i6zC2pViGWlH+KJGX8FHQ19IQGlUcljJk/Igo1EjWNgb4TvbjorXjKPaoMdMPA873I4NE818ONfbHG627b0UG6DoHKnF9b7kRb5VHS9ZuGpdH1mT7fEXxzW/L2OV6A/sDcqYgcvKunBeji0oqhvpGFD6G99QX8U7Wv91sbQ4No=
    admin-password: AgBYxmuKBA7gsaVsAJrDuSDq3zgjvJfpmxTP0wmOckHxcmg+1nRK8L88Ul4YKv1bnLzFgFLopa++cFW0rA6s20dCkTDJlMsJs7NZSWRdo8gZDtW5+mKoiIj5qyCtcJ8qZlj7Nx2qMrkqI11e5e1u7U2DHKuaMFfy9Xz99tYJR1BL7F5vKjVRVKBGN4vyYXlOE3bZ4+ZiMyUl+3YeAIxQOitHlxdR4VM4AYWInDagleiqfyf9U1zRIgKmaBrrxCdDA/G+bxqQz13W/wOT6aiQ9fB5ktL5eNANiqtauShR6nUnVo21KeVzpooc8xu5VBmehHMeZ8uwTrcovv3xP/j66NrrP8L3g5WNTiWJxWFvCymKtJW/eQC0SeQRpmr61Jhhrl9J/KQ4O8lffwh65Tcd7VQfDDcKRluJmuGBn1Fzh7PfSf2t9YM+ozgS7ebXWlfBLZSfgkTVaN3cJbOgEQad9XLSX12sczHE+OEzS9yTuJV6lNnTovg8Oz3Nm1o0vllvNK1NMQ3yiUu3RV6GjfT7YyqtOcoKX15bnvDqAktpfLUSwmYsP04jtBtBMx5LeWmQGzzqLupFr+msnLq0l3psm/9BmE7qsqf2wpmIWj4xvSLfoqepe7YfkibKu9Hihu9rr4hpjduI8gBxq2QMaQk/BpIJK0JZAH1pNIPciIvpQ2nZfAZVejnFS2AHyE6cDPJJF/1enWWYrHZUhYX32A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-password
      namespace: monitoring
    type: Opaque
