apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    adminPassword: AgAvqDnKs0kHwX7bLRNA/vt4SV3MdHzzS4CG7skaSn4mDkwOuvXpeGA+QsJEvhsETju3NtK+DrxwLkFTJw3GDS5zgaOKDlmYToAezNgVxfxR/iIT7HQzWwbaHHFspEJ4G1RtV9iRWwGus15XR+gJFVt1s73s6X6etqypxcJyO3szBiI0k3DRoZ6a38VMF+bAk7quf8CY72OBFcYA7rkmCjXv3aVaAPlIZrKiTDAsUZyk4ImkRC0xW35QjhrNw/KhVnYA/Pf8rOfwkkIsbkbYF5yzRCXQh4BKg/WWfxhbz97TngNyJx4LJS2Q5FL+jGJEPE9S2TV6LKotFqNOD9NNOe/Yccmf7u2s1BDoHM/pnvcCeOGwmC+2hRe2R19Xh7OmwCudqCgMSpvgW8A24mM54jvzmOkznM2OThZIjwHvZNHnXg0favpBIE49WHoq90Mc4ioA5EBrgpMQwA6Ua3jIS+N1dX1TATUGnkjNG5DxN0tKdIhovaOdWs4CcpQ54u7tEDDuHVCI+2DqNoJe4ke7xzDH8qPRzF6swdI+xwCIMhvuR1AHAvbiUIAQnGBtBfzd0HuaW+j/ymS+SNl0mdi35WzYofCHjJnOflPOrbHlc+sUG9/E5CI0MJTGc98np+aHkyMMimhQNVdZ+YUlHPcKwo/9iFRp3kh3tLcvNjCdV/q8KLXb5fiG+ARsMTwEwk3nJb8LMyp8S3LnQjZ2jQ==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
    type: Opaque
