---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    adminPassword: AgAWkfhzjQMH5c6bsnFv7a6wV6xJlssqtcOaqf3t5NT1aS2VgyO1NipxVRMzE+01uL1Cpl1g3eRoyYA2L9xDLCAlMcGRUoKeTh5rWHr5yChr5tmgVf+BTipNXB66i7YrCq9zZsedn0e+zHPh2hJSUnlyMeXMzTyG4XOUI3rP6BH81YhwT1Mu7Nwdnzl3+aN6j3w0t0NssJjWJP3lMtrPDctn/K+sZEOTToNdy4qILNq1vPzZtJ7dGSc4e3MnO7g0WextROQOu09B6LspbsBMgy3+dSyGtxe52A271Tz6ZTAQdA6YW5FEtvfzN2RDgnCaSU3aYfy2sE+Ck1i4a+TUMUbnRSAzjoKEEAGSM2UcTIpiSQRnccnjU/j8x0zNaFtkJyHesXIVJDoROuvPhXyVk36WPK37qG2xgJwuEHTus5VVMd/jIaCHBXcOAr1OnzFaBl7MRmP0xLVf+F6997YzSy2Z0JAwI6AGZDjjxjIzxmWNDo1Z98mJA35i0kfw+Nyxfd4/kcvS22bcv2E6JcX8JdXEGk/h7QFpLZkrIsIbQg+e1ECCRCQq6hmD3dLyluXpCOlL7Sqolc62rymWhYTsFxxffHzNwblNxGA4TBSH9sJgr8RZzQgY7O8IF/31N/4LsgwKv1vgz8Cxxne0R1H8yjMDtzluZRuYh9eMeaXGpBG/5wC9d1khqmbm8ZRHl3nhS14sjUAFsRsDhrroeQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-password
      namespace: monitoring
    type: Opaque
