apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-exporter-password
  namespace: monitoring
spec:
  encryptedData:
    pass: AgBJ7T9n0FSMEojbsLyh8eKV1MgE5/aUozKBrlo7QSVDcpWnVeX/Fvg0z1YaFid9rcf/783WiTboTPdVrw42n6216Rf996a8w7PQ5jVJOOYBnE+PKj44ZjAFGP5SQWKYa/POzMcMFoWhABvg0HgARTnZBuIkUPD8jI35qiAkCmDLFc29fjGnMunSaaDH21ypUzX6ssKDXIx34qAwN+xtDn5F6TbpDZi2KVga5Gf/vUtA5tEmBFnUgsZ6lgadGqZRT2wVF3MOkaQtzKYOxjYqVYSo0M9HJZ1g9c+yb13f+kU+c+TommDDbvQze903sUvIxiNj7YGDuxUYN0p0synBGvKtbBMMTU7mZS9F9yHldrrhOAlc08bVOrPv/lCD0K9c3uu6iTxNFVzaFFXoRvGcbnsm3CS6FLBrOzJ6JFt7FxtougacxDDrPew+AvdT6+dbx86JY+C2K5w8kYGaYRi+rz5ahOzHf5nb7KavBoV8uLN7Fv09Rdgd63QvqhdNcTO6M7jtougqfRY6z2uZi9q8r4ii+zAQxPLZZcCPoWtEI966wVN1SusGkeTtm9fTeLmHuhEeyZRe/RQWUzOecMy2m6d6XnfeFlqL+SVxGlfxKY7AZKjI8okSCTuNXHzQS4PgpeuczOV/EsNnE1zOcOLHU6UPWDY/D+YHSOOenFGcOMvemENoVlC5KSGru1hNyeeoMJb8/8ACTZmblyxmvQ==
  template:
    metadata:
      name: mysql-exporter-password
      namespace: monitoring
    type: Opaque
