---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-password
  namespace: monitoring
spec:
  encryptedData:
    password: AgBTBABEmZFnYEkn6H0q70zywZMFSIInkqqM4Mv5ktfck24PexTFXa/phmgoh2Jhee/hb/+z98+ZOO2sMdqKyVKFgebPWiQyC4m5KTY5b9Rw0G0aEY4w2kXYD6vIviz1bKS57iI7+ypCXcUYT1CyYBYUrWKDmT3QwEFVPegpbTExDnfo0LyS5fP5ftMkLwgzc73hdP8801npo4U+JaxTaf8o1noy6lkWi2yYKsLAfzpC21tf7+pF2AnqEba+ttriUPtkvoEbzA73Utm1KwPb1sihcQRhJ6S7DN3CKEiPPaMsED6NgO7Fk+r8BS3gMkMZqtuwjEuY3LquNI41XcTOopt0X/sXIML7pPDUuXCb4etl4zXPdbr21uey/HkhISU2XOyjsQzXRRw5oEMGpI4nCSD+jJqDP8if98MrSq20Cp4VMYvSVz5Ks1RK6WRQEuPI2n7MdZ3M5IpG07BMn7qgNHZWyEy7Gxbt2KxkdBQ+JNmk278nSyNL2gBN0Pn1dL9XyU6Baqc9jHhhLsvzryoK64+tzJtzwHWUXv6kNCFeGlycL0+JJR4yv+IlGMfYs6laMLz+ZTCZgKfo5diknM4KsIhIXmLYLlFbG+tObuj0UtvU3Mi/CI19+kjO2lxybAQZJ9YYn26CpiHkWjHTP2rTs9sxfuqS8VAR2E8OrETvDcUyYB0IKwt2KowUwmEeJgxeBZ2VDkzrW71y0yLnvQ==
  template:
    metadata:
      name: postgresql-password
      namespace: monitoring
