---
# SealedSecret for MariaDB password in analytics namespace
# This reuses the same encrypted password from mariadb namespace
# The encrypted value is the same, just namespace is different

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mariadb-password
  namespace: analytics
spec:
  encryptedData:
    db-password: AgAZ3HdIkl0hCcyFgrPke4w2+c10L7unCzonthrq7O1/SQ7rspN1BDME+QRg9cfiCtKfL4MOyOJQo+D3rRxp7mU7i55A11COOALNo5ujzcfbVhY1ndhEM3jbV/QvtWEa2VpoRry4AugyQT1nWYYQ6Xkx0KjNmNWjurk4gnlSH5iCdIug6cz1hMZWKMTqdJ3p7w8J58AcenwaLH7oTOxXWbhTzDubfQ8G0bjtwbLnn2dr3Sb6lW2CXdpwNMWw/UcdLh+lQHe7ZqnbuyadNdn59ujZkQRC9klRY5iX+OnuwH1Mf9tKhZ7s6tzXpin1CQfHvwPcq22WvfAa90w0YLXLkDp4/ed64CnyjAj9qz7m4+AB536UTdULsXfXHHS/7PTsc9QpCtCbna210Rs1OQFChAieCO+xOwkARp8eCH2tebV1m1rvt/m1cHsyt55IbsJJTpSq8N6LEJEFbaQR9DXzFLxDfRhulVaO9gGCcRYLUYv7/5vVvDkn0ocB+q5RMcbYEQ1TaQxkJtWsjnp1wV689nsfCEYBMxEBxoNTkBkJOURPEXYKbF8D3kwrdPX3ePhZHqqRbONwRcdTO1z6s08RxduKsEmMNhOsRGYfnjog6azBcioz+25pANvN2xIfpAJECxCDsw9Ce4Xw1wxf0D/5lvkrgWy+/L+2d8pdSek6MTwAY3LDOFDbHwKLKky1Fe/Y5CHtwP1mnzxjMXEzGQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mariadb-password
      namespace: analytics
    type: Opaque
