apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-backup
  namespace: gitea
spec:
  # Run backup every day at 2 AM
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: gitea/gitea:1.24.6
              command:
                - sh
                - -c
                - |
                  set -e
                  echo "Starting Gitea backup..."

                  # Create backup directory
                  mkdir -p /tmp/backup
                  cd /tmp/backup

                  # Run gitea dump to create backup
                  /usr/local/bin/gitea dump -c /etc/gitea/app.ini

                  BACKUP_FILE=$(ls -t gitea-dump-*.zip | head -1)
                  echo "Backup created: $BACKUP_FILE"

                  # Install MinIO client
                  wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /tmp/mc
                  chmod +x /tmp/mc

                  # Configure MinIO
                  /tmp/mc alias set minio ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}

                  # Create backup bucket if not exists
                  /tmp/mc mb -p minio/gitea-backups || true

                  # Upload backup to MinIO
                  /tmp/mc cp "$BACKUP_FILE" "minio/gitea-backups/$BACKUP_FILE"

                  # Keep only last 7 backups in MinIO
                  /tmp/mc ls minio/gitea-backups | sort -r | tail -n +8 | awk '{print $5}' | while read file; do
                    /tmp/mc rm "minio/gitea-backups/$file"
                  done

                  echo "Backup uploaded successfully to MinIO"
              env:
                - name: USER_UID
                  value: "1000"
                - name: USER_GID
                  value: "1000"
                - name: GITEA__database__DB_TYPE
                  value: "postgres"
                - name: GITEA__database__HOST
                  value: "postgresql-primary.postgresql.svc.cluster.local:5432"
                - name: GITEA__database__NAME
                  value: "gitea"
                - name: GITEA__database__USER
                  value: "postgres"
                - name: GITEA__database__PASSWD
                  valueFrom:
                    secretKeyRef:
                      name: gitea-postgres-password
                      key: password
                - name: MINIO_ENDPOINT
                  value: "http://minio.minio.svc.cluster.local:9000"
                - name: MINIO_ROOT_USER
                  valueFrom:
                    secretKeyRef:
                      name: minio-root-password
                      key: root-user
                - name: MINIO_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: minio-root-password
                      key: root-password
              volumeMounts:
                - name: gitea-data
                  mountPath: /data
                - name: gitea-config
                  mountPath: /etc/gitea
          volumes:
            - name: gitea-data
              persistentVolumeClaim:
                claimName: gitea
            - name: gitea-config
              configMap:
                name: gitea
