apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-backup
  namespace: gitea
spec:
  # Run backup every day at 2 AM
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
            # PostgreSQL backup container
            - name: postgres-backup
              image: postgres:15
              command:
                - sh
                - -c
                - |
                  set -e
                  echo "Starting PostgreSQL backup..."

                  mkdir -p /backup/db
                  cd /backup/db

                  # Get list of all databases
                  export PGPASSWORD="${POSTGRES_PASSWORD}"
                  DATABASES=$(psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -t -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                  # Backup each database
                  for db in $DATABASES; do
                    echo "Backing up database: $db"
                    pg_dump -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d $db -F c -f "${db}_$(date +%Y%m%d_%H%M%S).dump"
                  done

                  echo "PostgreSQL backup completed"
              env:
                - name: POSTGRES_HOST
                  value: "postgresql-primary.postgresql.svc.cluster.local"
                - name: POSTGRES_USER
                  value: "postgres"
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gitea-postgres-password
                      key: password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup

          containers:
            - name: backup
              image: gitea/gitea:1.24.6
              command:
                - sh
                - -c
                - |
                  set -e
                  echo "Starting Gitea backup..."

                  # Create backup directories
                  mkdir -p /backup/temp
                  cd /backup/temp

                  # Run gitea dump to create backup
                  /usr/local/bin/gitea dump -c /etc/gitea/app.ini

                  BACKUP_FILE=$(ls -t gitea-dump-*.zip | head -1)
                  echo "Backup created: $BACKUP_FILE"

                  # Extract gitea dump to separate components
                  unzip -q "$BACKUP_FILE"

                  # Create separate archives
                  mkdir -p /backup/repositories /backup/settings

                  # Archive repositories (gitea-repo directory)
                  if [ -d "gitea-repo" ]; then
                    cd gitea-repo
                    for repo in */; do
                      repo_name=$(basename "$repo")
                      echo "Archiving repository: $repo_name"
                      zip -r "/backup/repositories/${repo_name}_$(date +%Y%m%d_%H%M%S).zip" "$repo"
                    done
                    cd ..
                  fi

                  # Archive settings (app.ini and custom directory)
                  if [ -f "app.ini" ]; then
                    zip -r "/backup/settings/gitea-config_$(date +%Y%m%d_%H%M%S).zip" app.ini
                  fi
                  if [ -d "custom" ]; then
                    zip -r "/backup/settings/gitea-custom_$(date +%Y%m%d_%H%M%S).zip" custom/
                  fi

                  # Install MinIO client
                  wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /tmp/mc
                  chmod +x /tmp/mc

                  # Configure MinIO
                  /tmp/mc alias set minio ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}

                  # Create buckets if not exists
                  /tmp/mc mb -p minio/repositories || true
                  /tmp/mc mb -p minio/db || true
                  /tmp/mc mb -p minio/settings || true

                  # Upload repositories to MinIO
                  if [ -d "/backup/repositories" ] && [ "$(ls -A /backup/repositories)" ]; then
                    echo "Uploading repositories to MinIO..."
                    /tmp/mc cp --recursive /backup/repositories/* minio/repositories/
                  fi

                  # Upload database backups to MinIO
                  if [ -d "/backup/db" ] && [ "$(ls -A /backup/db)" ]; then
                    echo "Uploading database backups to MinIO..."
                    /tmp/mc cp --recursive /backup/db/* minio/db/
                  fi

                  # Upload settings to MinIO
                  if [ -d "/backup/settings" ] && [ "$(ls -A /backup/settings)" ]; then
                    echo "Uploading settings to MinIO..."
                    /tmp/mc cp --recursive /backup/settings/* minio/settings/
                  fi

                  # Keep only last 7 backups in each bucket
                  for bucket in repositories db settings; do
                    echo "Cleaning old backups in $bucket..."
                    /tmp/mc ls minio/$bucket | sort -r | tail -n +8 | awk '{print $5}' | while read file; do
                      if [ -n "$file" ]; then
                        /tmp/mc rm "minio/$bucket/$file"
                      fi
                    done
                  done

                  echo "Backup completed successfully"
              env:
                - name: USER_UID
                  value: "1000"
                - name: USER_GID
                  value: "1000"
                - name: GITEA__database__DB_TYPE
                  value: "postgres"
                - name: GITEA__database__HOST
                  value: "postgresql-primary.postgresql.svc.cluster.local:5432"
                - name: GITEA__database__NAME
                  value: "gitea"
                - name: GITEA__database__USER
                  value: "postgres"
                - name: GITEA__database__PASSWD
                  valueFrom:
                    secretKeyRef:
                      name: gitea-postgres-password
                      key: password
                - name: MINIO_ENDPOINT
                  value: "http://minio.minio.svc.cluster.local:9000"
                - name: MINIO_ROOT_USER
                  valueFrom:
                    secretKeyRef:
                      name: minio-root-password
                      key: root-user
                - name: MINIO_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: minio-root-password
                      key: root-password
              volumeMounts:
                - name: gitea-data
                  mountPath: /data
                - name: gitea-config
                  mountPath: /etc/gitea
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: gitea-data
              persistentVolumeClaim:
                claimName: gitea-shared-storage
            - name: gitea-config
              configMap:
                name: gitea
            - name: backup-storage
              emptyDir: {}
