---
apiVersion: v1
kind: Namespace
metadata:
  name: homer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      initContainers:
      - name: copy-assets
        image: alpine/git:latest
        command: ['sh', '-c']
        args:
          - |
            # Git에서 assets 복사
            git clone --depth 1 --branch main https://github.com/Mayne0213/infrastructure.git /tmp/repo
            # assets 폴더 복사
            cp -r /tmp/repo/homer/assets /www/assets
            # config.yml 복사
            cp /config/config.yml /www/assets/config.yml
        volumeMounts:
        - name: config
          mountPath: /config
        - name: www
          mountPath: /www
      containers:
      - name: homer
        image: b4bz/homer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: www
          mountPath: "/www"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: homer-config
      - name: www
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: homer
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: homer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer-ingress
  namespace: homer
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mayne.kro.kr
    - www.mayne.kro.kr
    secretName: homer-tls
  rules:
  - host: mayne.kro.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homer
            port:
              number: 80
  - host: www.mayne.kro.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homer
            port:
              number: 80
