apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgweb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    - repoURL: https://github.com/Mayne0213/infrastructure.git
      targetRevision: main
      path: pgweb
  
  destination:
    server: https://kubernetes.default.svc
    namespace: pgweb
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
