apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minjyo/infrastructure.git
    targetRevision: HEAD
    path: proxysql
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

