---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mariadb-replication-password
  namespace: mariadb
spec:
  encryptedData:
    mariadb-replication-password: AgAPKV2e+1xfKOlXSL/6/OWyBXj26VWXR5Ou5lqVZbIFtagHN4tDXAwkpxhgxf4zwPR6HZQ9qeDwSGA3BTXPazz5Uy3bk3OdIZkbhmU2rlnm/JJgntTh5RVSM74cvG5yY1BBXhpZBUoXHBfHiecoRjKAIvM46IGacq2I405jpswvmqTNa/hAZjJNKSSGYpJ3yPBKh49S4jnE1QR1zLf+KKmT8yRNqNcB+Y3dh4HceNUSZmy2Q1jOheKMwub6mF8k9T3N//w02fr7XKIejt7FvS/r8DAfu5QOZ8tIVxyW3SOl+rxrGL+YFeH0LERgywY1oJ+T6C6ugjqppYbjxi1/F2BnTsg7PkdTYip2DKQD75VnvTBt6RtAJLrhVcZakeudTcqP+YwBDHgcx/hT1nSh8wIxWrUZe8YOX1Pm1uRQYB9kV09qT5fcMWkVw1rA+nS2p42AqDuqXxc/ZIvVM5bE2BBSbUjV3UFFy9MXW2xBGUQq9iHKIFKZrLsGjAhDdc3TUbqc2+p5zPIRFbkTp1HnlMNnVhdSIXtPyM7q9wf9p6m1oSeMAvRukNrYmLIORnfdstPkDxJhMYXa5l7ABnmpkyHFIqUH+S7ZBwBxDo2BfbEmtCojmyijvJbt70Xps3iNHF51ECYewLc07ZXveP2NrORyOflmUJu7+JKw5NsGgmB8CBG+V9kpxHQ6mB2by+70rPYMmtli8j68BmoQSg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mariadb-replication-password
      namespace: mariadb
    type: Opaque
