apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxysql-monitor-password
  namespace: mariadb
spec:
  encryptedData:
    monitorPassword: AgCKZUBXYu+2B0+qi0cdHora9YrsUnvTJ3rGzXrLnlRziyqElP/l+FNSDkDbZzPM3lJpovB7U3yRzbJ3TJhLmmFuYcOF9w/wdZOBCsacuXiL4FRu2UlihMEC9a4P9M1aoABhlokXOnhRI6xIq0lZLCNvZz/s5VWWJ2Aqe84fo7ZAcC9nuRH/ezxzM+4qc4DD/NW5XWW8vUvzV+D+HKFBLElCSsE0fNpitBoQFy0pewVKA67lg1ZZzD+45JuzqlVEKd0X5VCla4tApcRGrryUnnFvjEFXbCDVnPW5PqpQPdf2E3eAO6c8PYMIojT2AD+uE/oFDaJDfNBvl71hFLoDeUf14mtYlTyHfd422mE2j3YoTIa+PNiIGKAb7w/fhEIpONmzE/FVhtfgYYdZ7rJbi8iAXBs+MLWUwNEK5+xvivvqeE8AdkSkBRyJXiepnihPVL23Y+4H2+fgBkBhq1AgxlyVVAgvbIZwUlQe9BrkF+1iDRT9kLQQnL96DDv4Z9mzhUxH80hqkeWgfsbAWgB55nS0UDT6D0zRZUBT+aUrj7waS9XN5PZjokmERnDx+YfUXhQQ9RjMzkgQ3+1V7LSKS0qiyEon/kvNmWL95Mp7qLu6fr8nU/W+cLfbijdwfu98qBPXtP80P2EkqwqymZY3L1zcgf00FzFVG+WAJ6WPwyJ81iCb6ZOXHPseqsSaET9OyI6/QE89YJh7PZ3TGg==
  template:
    metadata:
      name: proxysql-monitor-password
      namespace: mariadb
    type: Opaque
