---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: proxysql-admin-password
  namespace: mariadb
spec:
  encryptedData:
    admin-password: AgBYNG9tq+Rkox21zD86k0eehz4ktpL8/gMKRj3s7Pvc9OeY5uvrwT/PvcnuGMQjG8iP0WEC78Jvqz3tT3C4ihFBerC/lvfcQj4thvOLV+f6GdWeQswY59Ik/b1qGqdzc7d/gWJmQFAezFZZVMsDcc31vl68E4KRQYSr8MIcSL3txOvYrDHCXpBl+MVYrk17f5TJDGAYKOlpRpDkz7DtKck5wAXvz8lDq5yqZhAVLjw8ZskatiNWYrxl6FiqbT4PzMbmTCnkgoNsEWQsqQRa4xiQXC0ZlnZnRsqg7v/AIPmURh8/I+gZ3TbV5sr1XNx2GLaccJVH+niKtONfsFoZ6xZY1EXZ0119TYwU1LPFj34brd452D2E2qbHpK31dNA+suSF0dTeTq/Gojwdq/xkx9PmlHRoX1mnCUb+1VD0D7UuMmDLPpYefop0mvRDWhokJJg/HjVmlkVjj5IYcz0HJadzndbNGXqd6xWdZlr/iKc+A2hPPgadI7q1J+PfC0Bz1Uw3l4X3TTEXPgGA66AqJ6ZyPR2n4YlsNZCImuz1vnVFcZt3xVcGdJUH+7X8x0AWHvptb9Ejm2PlQe3CBDU9pw7wHvnKcezveVGfGR6m7REcTePGJIKrOzS7+pMli+omtG/3tvOhP+DUy/Wr3t1SYcCh8Ickio4NZAXqsERd3Eu8yL1s8dZQVhoZ1SvStskbnm5EXjUUSv/Al4tLKQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: proxysql-admin-password
      namespace: mariadb
    type: Opaque
