---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: proxysql-monitor-password
  namespace: mariadb
spec:
  encryptedData:
    monitorPassword: AgBDM1OHQE2VCjcTNdiaDYn4AANof6F+ZCb2/aodCdovT61MfmgezexG/omClNUX0EF8jJliroFqZ7Qw3dc+yYZ8ODCIhYOnO+JQKlVr7v1H/md4CEON4/3+EqN/0J1tIBFC59mP2wt5U6yQ0AQbwqsHw+M1869k2rb6ikD5VKSDsYbRlmR4EUXn4XleyI3tNY3y78XgRUIgD6uiuI+Ny1ShbM0+Ra2i5NCLi8YUnbSgC3E0MYV3U2YegMchqa6A6yMMkUrBi8LngLF1BXKHhcKK9IY5tRtJtaBNQkF8LTzu0Yj57Wg69hoF67VrHFzXLH6rAiWgvrwszw6FFG+uzCv97AnF8vf1/YcXz/zdcES8cdpNZ0PQ/+gNYi6GSDHQW+VBurN8iTGoirTQU4bCyQqQp3i+D27CPnN66UGebgH1vHeX9zPZ+kfyGTRkb0AgIGyIauDSw8Mtbi1GLkJBwoMh7Xj6B6Pl9LFGW95TDMhtY+DOiugpPvYLwK6stl5PcOzrVF7cawI+//dfZvJMMeGZ7+YVkI9W9Ba2c9SNEUs0+JPtLJKMgxW4CsEnxKPjlDw+JxiCVlg33QSsnhh2t4dX5NFm1Jw9xegREVSyrWCX7MgTTUO2YhBXk7w7Tdb+Rmp3swqYddMr7MWLtPHEOTReopf+2qCIk1wbdqW0IRf+Ifbp9MZsJbeWTpsLBIjOK2QN1N0qK76i3vEwNQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: proxysql-monitor-password
      namespace: mariadb
    type: Opaque
