apiVersion: v1
kind: Service
metadata:
  name: mysql-dev
  namespace: mysql
  labels:
    app: mysql
    env: dev
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql
    env: dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-dev
  namespace: mysql
spec:
  serviceName: mysql-dev
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      env: dev
  template:
    metadata:
      labels:
        app: mysql
        env: dev
    spec:
      nodeSelector:
        kubernetes.io/hostname: mayne-vcn
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "dev-password"
            - name: MYSQL_DATABASE
              value: "devdb"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-dev-pvc
