apiVersion: v1
kind: Secret
metadata:
  name: mysql-backup-minio-credentials
  namespace: mysql
type: Opaque
stringData:
  access-key: "Zp1ZCmJvB6kRWKkTzmyy"
  secret-key: "6VHJ1mHxRSdc0UBtVEva0fsT0LMXIbnPFvF9Wz7f"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: mysql
spec:
  # 매주 일요일 오전 3시 (KST 기준 정오 12시)
  schedule: "0 3 * * 0"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: mysql-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: alpine:3.19
            command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "=== MySQL Backup Started at $(date) ==="

              # Install dependencies
              apk add --no-cache mysql-client curl

              # Install MinIO client (ARM64)
              curl -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-arm64/mc
              chmod +x /usr/local/bin/mc

              # Configure MinIO
              mc alias set minio http://minio.minio.svc.cluster.local:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

              # Create backup directory
              BACKUP_DATE=$(date +%Y%m%d_%H%M%S)
              BACKUP_DIR="/tmp/mysql-backup-$BACKUP_DATE"
              mkdir -p $BACKUP_DIR

              echo "=== Backing up databases ==="

              # Backup each database
              for DB in JaejadleDB TodoListDB; do
                echo "Backing up $DB..."
                mysqldump -h mysql-primary-0.mysql-primary.mysql.svc.cluster.local \
                  -u root -p${MYSQL_ROOT_PASSWORD} \
                  --single-transaction \
                  --routines \
                  --triggers \
                  --events \
                  --databases $DB \
                  > $BACKUP_DIR/${DB}.sql

                if [ $? -eq 0 ]; then
                  echo "✓ $DB backup successful"
                else
                  echo "✗ $DB backup failed"
                  exit 1
                fi
              done

              # Compress backups
              echo "=== Compressing backups ==="
              cd /tmp
              tar -czf mysql-backup-$BACKUP_DATE.tar.gz mysql-backup-$BACKUP_DATE/

              # Upload to MinIO
              echo "=== Uploading to MinIO ==="
              mc cp mysql-backup-$BACKUP_DATE.tar.gz minio/mysql-backup/

              if [ $? -eq 0 ]; then
                echo "✓ Upload successful"
              else
                echo "✗ Upload failed"
                exit 1
              fi

              # Cleanup old backups (keep last 4 weeks)
              echo "=== Cleaning up old backups ==="
              mc rm --recursive --force --older-than 28d minio/mysql-backup/ || true

              # Cleanup local files
              rm -rf $BACKUP_DIR mysql-backup-$BACKUP_DATE.tar.gz

              echo "=== Backup completed successfully at $(date) ==="
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-backup-minio-credentials
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-backup-minio-credentials
                  key: secret-key
            resources:
              requests:
                memory: "256Mi"
                cpu: "50m"
              limits:
                memory: "1Gi"
                cpu: "150m"
