---
# Replica 1 Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica1
  namespace: mysql
  labels:
    app: mysql
    role: replica
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql
    role: replica
    instance: replica1
---
# Replica 1 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica1
  namespace: mysql
spec:
  serviceName: mysql-replica1
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: replica
      instance: replica1
  template:
    metadata:
      labels:
        app: mysql
        role: replica
        instance: replica1
    spec:
      nodeSelector:
        kubernetes.io/hostname: mayne-worker-1
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          command:
            - bash
            - "-c"
            - |
              echo -e "[mysqld]\nserver-id=2" > /etc/mysql/conf.d/server-id.cnf
              exec docker-entrypoint.sh mysqld
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d/replica.cnf
              subPath: replica.cnf
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - mysql -u root -p${MYSQL_ROOT_PASSWORD} -h localhost -e "SELECT 1"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: config
          configMap:
            name: mysql-config
            items:
              - key: replica.cnf
                path: replica.cnf
        - name: data
          persistentVolumeClaim:
            claimName: mysql-prod-replica1-pvc
---
# Replica 2 Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica2
  namespace: mysql
  labels:
    app: mysql
    role: replica
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql
    role: replica
    instance: replica2
---
# Replica 2 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica2
  namespace: mysql
spec:
  serviceName: mysql-replica2
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: replica
      instance: replica2
  template:
    metadata:
      labels:
        app: mysql
        role: replica
        instance: replica2
    spec:
      nodeSelector:
        kubernetes.io/hostname: mayne-worker-1
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          command:
            - bash
            - "-c"
            - |
              echo -e "[mysqld]\nserver-id=3" > /etc/mysql/conf.d/server-id.cnf
              exec docker-entrypoint.sh mysqld
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d/replica.cnf
              subPath: replica.cnf
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - mysql -u root -p${MYSQL_ROOT_PASSWORD} -h localhost -e "SELECT 1"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: config
          configMap:
            name: mysql-config
            items:
              - key: replica.cnf
                path: replica.cnf
        - name: data
          persistentVolumeClaim:
            claimName: mysql-prod-replica2-pvc
