apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
stringData:
  # Change these passwords in production
  root-password: "changeme-root-password"
  replication-password: "changeme-repl-password"
