---
# Production MySQL Primary - Block Volume on master
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-prod-primary-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/mysql-prod
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - oracle-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-prod-primary-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 30Gi
  volumeName: mysql-prod-primary-pv
---
# Development MySQL - Block Volume on master
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dev-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/mysql-dev
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - oracle-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dev-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-dev-pv
---
# Replica 1 - Worker1 Boot Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-prod-replica1-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/mysql-replica
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - oracle-worker1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-prod-replica1-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 30Gi
  volumeName: mysql-prod-replica1-pv
---
# Replica 2 - Worker2 Boot Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-prod-replica2-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/mysql-replica
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - oracle-worker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-prod-replica2-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 30Gi
  volumeName: mysql-prod-replica2-pv
